services:
  postgres:
    image: postgres
    container_name: duolibras-postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: duolibras-postgres
      POSTGRES_PASSWORD: duolibras-postgres
      POSTGRES_DB: duolibras-db
